name: DevSecOps Purple Pipeline

on:
  push:
    branches: [ "principal", "main", "master" ]
  pull_request:
    branches: [ "principal", "main", "master" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build da Aplicação com Maven
        run: mvn clean install -DskipTests

      - name: Executar Aplicação em Segundo Plano
        run: mvn spring-boot:run & sleep 60

      - name: RED TEAM - Teste de Injecao no Endpoint VULNERAVEL
        continue-on-error: true
        run: |
          echo "Simulando ataque de injecao..."
          curl -s -v "http://localhost:8080/api/users/vulnerable?id=1%27"

      - name: RED TEAM - Teste de Injecao no Endpoint SEGURO
        run: |
          echo "Tentando o mesmo ataque no seguro..."
          curl -s -v "http://localhost:8080/api/users/safe?id=1%27"

      - name: BLUE TEAM & GRC - Verificacao final
        run: |
          echo "Analise concluida com sucesso."